Repository 16-team/16-team, pull requests merged in 2023-09, with the labels that each got.

#1 [FEAT] : ContactListFragment UI(Adapter), ContactListFragment UI(Adap…
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/com/example/contacts/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feat

#5 [Fix] : </androidx.constraintlayout.widget.ConstraintLayout> 추가
  app/src/main/res/layout/fragment_contact.xml
Labels: bug

#6 [feat] : contentDialog
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/java/com/example/contacts/MainActivity.kt
  app/src/main/res/drawable/dialog_bt.xml
  app/src/main/res/drawable/me.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/add_contact_dialog.xml
Labels: feat

#7 [Feat] : RecyclerView ItemClick이벤트 전달기능 완료
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/contacts/ContactAdapter.kt
  app/src/main/java/com/example/contacts/ContactFragment.kt
  app/src/main/java/com/example/contacts/DetailActivity.kt
  app/src/main/java/com/example/contacts/DetailFragment.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_main.xml
Labels: feat

#8 [design] : GridView ui 배치 & 그리드뷰 어댑터 코드추가
  app/src/main/java/com/example/contacts/ContactAdapter.kt
  app/src/main/java/com/example/contacts/ContactFragment.kt
  app/src/main/java/com/example/contacts/ContactManager.kt
  app/src/main/res/drawable/bbosi.png
  app/src/main/res/drawable/donge.png
  app/src/main/res/drawable/gyeonhwa2.png
  app/src/main/res/drawable/latte.png
  app/src/main/res/drawable/minsu2.png
  app/src/main/res/drawable/sejun2.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_contact.xml
  app/src/main/res/layout/rv_grid_item.xml
  app/src/main/res/layout/rv_item.xml
Labels: design

#9 Feature/add contact dialog
  app/src/main/java/com/example/contacts/ContactFragment.kt
  app/src/main/java/com/example/contacts/ContactManager.kt
  app/src/main/res/layout/add_contact_dialog.xml
  app/src/main/res/layout/fragment_contact.xml
Labels: feat

#10 [Feat] : seach bar 기능,더미데이터약간의 디자인
  app/src/main/java/com/example/contacts/ContactAdapter.kt
  app/src/main/java/com/example/contacts/ContactFragment.kt
  app/src/main/java/com/example/contacts/ContactManager.kt
  app/src/main/res/drawable/baseline_search_24.xml
  app/src/main/res/drawable/gyeonghwa2.jpg
  app/src/main/res/drawable/gyeonhwa2.png
  app/src/main/res/drawable/latte.png
  app/src/main/res/drawable/minsu2.png
  app/src/main/res/drawable/sejun2.png
  app/src/main/res/drawable/seounghyun2.png
  app/src/main/res/layout/fragment_contact.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: feat

#11 Feature/data parcelization
  app/build.gradle
  app/src/main/java/com/example/contacts/Contact.kt
  app/src/main/java/com/example/contacts/ContactFragment.kt
  app/src/main/java/com/example/contacts/DetailActivity.kt
  app/src/main/res/drawable/add_selector.xml
  app/src/main/res/drawable/baseline_arrow_back_24.xml
  app/src/main/res/drawable/btn_message_pressed.xml
  app/src/main/res/drawable/unclicked_call.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/dimens.xml
Labels: feat

#12 Design/search bar,feat/if문
  app/src/main/java/com/example/contacts/ContactAdapter.kt
  app/src/main/java/com/example/contacts/ContactFragment.kt
  app/src/main/res/drawable/clicked_grid.png
  app/src/main/res/drawable/clicked_list.png
  app/src/main/res/drawable/uncilcked_grid.png
  app/src/main/res/drawable/unclicked_list.png
  app/src/main/res/layout/fragment_contact.xml
Labels: feat

#14 Feature/add contact dialog
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/contacts/ContactFragment.kt
  app/src/main/res/drawable/clicked_grid.png
  app/src/main/res/drawable/clicked_list.png
  app/src/main/res/drawable/uncilcked_grid.png
  app/src/main/res/drawable/unclicked_list.png
Labels: feat

#16 [MERGE] : Swipe, 기타 디자인 수정 작업
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/contacts/ContactFragment.kt
  app/src/main/java/com/example/contacts/ItemTouchHelperCallback.kt
  app/src/main/res/layout/activity_detail.xml
Labels: feat

#17 Feature/function packaging
  app/src/main/java/com/example/contacts/Adapter/ContactAdapter.kt
  app/src/main/java/com/example/contacts/ContactFragment.kt
  app/src/main/java/com/example/contacts/ContactManager.kt
  app/src/main/java/com/example/contacts/DetailActivity.kt
  app/src/main/java/com/example/contacts/ItemTouchHelperCallback.kt
  app/src/main/java/com/example/contacts/MainActivity.kt
  app/src/main/java/com/example/contacts/MyPageFragment.kt
  app/src/main/java/com/example/contacts/Util/CommonUtils.kt
  app/src/main/java/com/example/contacts/ViewPager2.kt
  app/src/main/java/com/example/contacts/data/Contact.kt
  app/src/main/java/com/example/contacts/data/ContactManager.kt
Labels: feat

#18 Fix/item cilck
  app/src/main/java/com/example/contacts/ContactFragment.kt
  app/src/main/java/com/example/contacts/ContactManager.kt
Labels: feat

#19 Feature/add contact dialog
  app/src/main/java/com/example/contacts/ContactFragment.kt
  app/src/main/java/com/example/contacts/ContactManager.kt
  app/src/main/java/com/example/contacts/Util/CommonUtils.kt
  app/src/main/java/com/example/contacts/data/Contact.kt
  app/src/main/java/com/example/contacts/data/ContactManager.kt
Labels: feat

#21 [DESIGN] : 탭레이아웃수정
  app/src/main/res/layout/activity_main.xml
Labels: design

#22 [Fix] : 북마크해제시 전체 해제되는거 수정,[Fix] : 검색기능에서 자음만 검색시 자음포함된 모든글자 나오게수정
  app/src/main/java/com/example/contacts/ContactFragment.kt
  app/src/main/java/com/example/contacts/DetailActivity.kt
  app/src/main/res/layout/fragment_contact.xml
Labels: bug

#23 Feature/send message
  app/src/main/java/com/example/contacts/DetailActivity.kt
  app/src/main/java/com/example/contacts/Util/CommonUtils.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: feat

#24 Feature/add contact dialog
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/contacts/Adapter/ContactAdapter.kt
  app/src/main/java/com/example/contacts/ContactFragment.kt
  app/src/main/java/com/example/contacts/Util/CommonUtils.kt
  app/src/main/java/com/example/contacts/data/ContactManager.kt
Labels: feat

#25 Feature/add contact dialog
  app/src/main/java/com/example/contacts/ContactFragment.kt
  app/src/main/java/com/example/contacts/DetailActivity.kt
  app/src/main/res/drawable/un_selsected_image.webp
  app/src/main/res/layout/add_contact_dialog.xml
Labels: bug, feat

#27 Feature/import contacts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/contacts/Adapter/ContactAdapter.kt
  app/src/main/java/com/example/contacts/ContactFragment.kt
  app/src/main/java/com/example/contacts/DetailActivity.kt
  app/src/main/java/com/example/contacts/MainActivity.kt
  app/src/main/java/com/example/contacts/Util/CommonUtils.kt
  app/src/main/java/com/example/contacts/data/ContactManager.kt
Labels: feat

#28 Feature/splash
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/contacts/ContactFragment.kt
  app/src/main/java/com/example/contacts/SplashActivity.kt
  app/src/main/res/layout/activity_splash.xml
Labels: feat

#29 Feature/mypage&sorted
  app/src/main/java/com/example/contacts/EditMyPageFragment.kt
  app/src/main/java/com/example/contacts/MyPageFragment.kt
  app/src/main/res/layout/fragment_edit_my_page.xml
Labels: feat

#30 [DESIGN]:swipe 디자인
  app/src/main/java/com/example/contacts/ContactFragment.kt
  app/src/main/java/com/example/contacts/ItemTouchHelperCallback.kt
  app/src/main/res/drawable/swipe_border.xml
  app/src/main/res/layout/rv_item.xml
  app/src/main/res/layout/tab_item.xml
Labels: design

#31 [FIX]:swipe 버그 수정
  app/src/main/java/com/example/contacts/Adapter/ContactAdapter.kt
  app/src/main/java/com/example/contacts/ContactFragment.kt
  app/src/main/java/com/example/contacts/ItemTouchHelperCallback.kt
Labels: bug

#32 Fix/import contact
  app/src/main/java/com/example/contacts/ContactFragment.kt
  app/src/main/java/com/example/contacts/data/Contact.kt
  app/src/main/res/values/strings.xml
Labels: feat

#33 Feature/noti2
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/contacts/ContactFragment.kt
  app/src/main/java/com/example/contacts/Notification/NotificationHelper.kt
  app/src/main/java/com/example/contacts/Notification/NotificationReceiver.kt
  app/src/main/java/com/example/contacts/data/Contact.kt
  app/src/main/java/com/example/contacts/data/ContactManager.kt
  app/src/main/res/layout/add_contact_dialog.xml
Labels: feat

#34 Feature/noti cancle btn 기능구현
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/contacts/ContactFragment.kt
  app/src/main/java/com/example/contacts/DetailActivity.kt
  app/src/main/java/com/example/contacts/Notification/NotificationHelper.kt
  app/src/main/java/com/example/contacts/Notification/NotificationReceiver.kt
  app/src/main/java/com/example/contacts/data/ContactManager.kt
  app/src/main/res/drawable/baseline_add_ic_call_24.xml
  app/src/main/res/layout/add_contact_dialog.xml
Labels: feat

#35 [Fix] : snackBar메시지 가운데정렬
  app/build.gradle
  app/src/main/java/com/example/contacts/DetailActivity.kt
  app/src/main/res/layout/add_contact_dialog.xml
  app/src/main/res/layout/fragment_contact.xml
Labels: bug, design

#38 [Design] : Contact Toolbar
  app/src/main/res/layout/fragment_contact.xml
Labels: feat

#40 Feature/contact edit
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/contacts/Adapter/ContactAdapter.kt
  app/src/main/java/com/example/contacts/ContactFragment.kt
  app/src/main/java/com/example/contacts/DetailActivity.kt
  app/src/main/java/com/example/contacts/EditMyPageFragment.kt
  app/src/main/java/com/example/contacts/ItemTouchHelperCallback.kt
  app/src/main/java/com/example/contacts/MainActivity.kt
  app/src/main/java/com/example/contacts/MyPageFragment.kt
  app/src/main/java/com/example/contacts/Notification/NotificationHelper.kt
  app/src/main/java/com/example/contacts/Notification/NotificationReceiver.kt
  app/src/main/java/com/example/contacts/data/Contact.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/edit_dialog.xml
  app/src/main/res/layout/fragment_edit_my_page.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/rv_item.xml
  app/src/main/res/values/strings.xml
Labels: feat

#41 [DESIGN]:다이얼로그 페이지 수정
  app/src/main/res/layout/add_contact_dialog.xml
Labels: design

#45 [DESIGN]:Splash
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/contacts/SplashActivity.kt
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/raw/mss.json
Labels: design
